version: '3.8'

services:
  # Redis Service
  redis:
    image: redis/redis-stack-server:latest
    container_name: geotrack_redis
    ports:
      - "6379:6379"
    restart: always

  # FastAPI Service
  web:
    build: .
    container_name: geotrack_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always